### PR TITLE
Config variable added

### PR DESCRIPTION
**Pull request by csutorasr**
I made the changes to the config variable.

The version is increased as the new feature.

### CODE REVIEW

**Comment by csutorasr** [comment]
The test cannot find the injection token, but as a program it is working. I cannot tell what the problem is with the test.

**Comment by odahcam** [comment]
You simply don't need a config variable, once this is a component, you should be using `@Input` and `@Output`. That's not what we want and we are not mantaining `v0.x.x` at the moment.

Something like this was already added to `v1.0.0-dev`, you can check it out on the develop branch. 😉

**Comment by odahcam** [comment]
Please, note that it was added as `@Input`:

https://github.com/werthdavid/ngx-zxing/blob/bdef0e561b6633f325998029af0ab1320e444174/src/app/modules/ngx-zxing/ngx-zxing.component.ts#L60-L64

You cna make some tests by adding this property instantiation to construct:

https://github.com/werthdavid/ngx-zxing/blob/bdef0e561b6633f325998029af0ab1320e444174/src/app/modules/ngx-zxing/ngx-zxing.component.ts#L30-L33

I did that and I removed after because I noticed too much performance issues. but that's the way it should be done in the "Angular way".

Thanks again for your enfort, you are free to play with the develop branch, which is already stable. 😁

**Comment by csutorasr** [comment]
I was told to solve it in issue #24 .

**Comment by odahcam** [comment]
Sorry, but that's not a solution we can accept. Also the issue is in milestone `v1.0...` and not `v0.x...`.

**Comment by werthdavid** [comment]
@csutorasr what is the advantage of the injection token over the current solution with @Inputs and @Outputs as stated by @odahcam ?

We're currently doing lot's of rework as you can see in development branch. As you can see there exists a possibility to change the throttling behavior

**Comment by csutorasr** [comment]
Its advantage: no performance issues.

Its disadvantage: cannot be changed (can be configured only once).

**Comment by werthdavid** [comment]
Is performance really an issue? 
I'd suggest to set ChangeDetectionStrategy to OnPush, this should increase performance. I'll create an issue for that

**Pull request closed without merging**
