### PR TITLE
Fix windows 10 mobile issue and add debug mode

### PR DESCRIPTION
**Pull request by Nightapes**

### CODE REVIEW

**Comment by werthdavid** [comment]
Hey, @Nightapes thanks for the PR!
I don't know if you have seen it, but we're in the last steps of releasing a stable 1.0.0 version (see develop-branch). I really appreciate the PR but I'd like to wait until we have finished the work there b/c I think that most of the stuff will become obsolete then.

**Comment by odahcam** [comment]
The changes looks interesting, but I think them all are solved in v1.x. Otherwise, we should take a look at the peerDependencies config.

**Comment by Nightapes** [comment]
@werthdavid  thanks for your answer. I will have a look when 1.0.0 is out and make a new PR

**Comment by werthdavid** [comment]
@Nightapes 1.0.0 is out, if there is anything to complain about, contribution is greatly appreciated :wink:

**Pull request closed without merging**
